### ISSUE TITLE
Location select drop-down doesn't work as expected on mobile 

### ISSUE THREAD

**Issue by stanchanpsu** [stanchanpsu/whencanipickle#28]
![Screenshot_20240805-150158.png](https://github.com/user-attachments/assets/c5f0a7af-99a4-451a-a16e-32ec57542357)

I see that the suggestions come up on Android keyboard as text suggestions but I think that might be a bit confusing for users. I wonder if we can change this back to a webpage drop-down. How does it show up on iOS?

**Comment by stanchanpsu** [comment]
![Screenshot_20240805-150703.png](https://github.com/user-attachments/assets/48e44e7c-7fb3-4fba-a4b7-e84c79557a6a)

It would be cool to have both.

**Comment by ddamato** [comment]
Yeah, we'll need to roll our own on this one. The native `<details/>` pattern just isn't cutting it.
